// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTracking.PresentationLayer.DAL;

namespace TaskTracking.PresentationLayer.Migrations
{
    [DbContext(typeof(TaskTrackingContext))]
    partial class TaskTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTracking.PresentationLayer.Entities.CalendarEntity", b =>
                {
                    b.Property<int>("calender_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emp_ID")
                        .HasColumnType("int");

                    b.Property<string>("events")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("calender_ID");

                    b.HasIndex("emp_ID");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("TaskTracking.PresentationLayer.Entities.Employee", b =>
                {
                    b.Property<int>("emp_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TaskTracking.PresentationLayer.Entities.CalendarEntity", b =>
                {
                    b.HasOne("TaskTracking.PresentationLayer.Entities.Employee", "Employees")
                        .WithMany("Calendars")
                        .HasForeignKey("emp_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
